[phases.setup]
nixPkgs = ["python312", "nodejs_22", "pnpm"]

[phases.install]
cmds = [
  "cd api && pip install uv && uv sync --locked",
  "cd web && npm install -g pnpm && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd web && pnpm build"
]

[start]
cmd = "cd api && python app.py" 