[project]
name = "dify"

[services.api]
name = "dify-api"
source = "api"
buildCommand = "echo 'Building API service...'"
startCommand = "python app.py"
port = 5001

[services.web]
name = "dify-web"
source = "web"
buildCommand = "pnpm install && pnpm build"
startCommand = "pnpm start"
port = 3000

[services.postgres]
name = "dify-postgres"
type = "postgresql"
version = "16"

[services.redis]
name = "dify-redis"
type = "redis"
version = "7"

[services.weaviate]
name = "dify-weaviate"
type = "weaviate"
version = "1.22.4"

[env]
# Database Configuration
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "difyai123456"
POSTGRES_DB = "dify"
POSTGRES_HOST = "{{services.postgres.internalHost}}"
POSTGRES_PORT = "{{services.postgres.port}}"

# Redis Configuration
REDIS_HOST = "{{services.redis.internalHost}}"
REDIS_PORT = "{{services.redis.port}}"
REDIS_PASSWORD = "difyai123456"

# Weaviate Configuration
WEAVIATE_HOST = "{{services.weaviate.internalHost}}"
WEAVIATE_PORT = "{{services.weaviate.port}}"

# Dify Configuration
EDITION = "SELF_HOSTED"
DEPLOY_ENV = "PRODUCTION"
FLASK_APP = "app.py"

# API URLs
CONSOLE_API_URL = "https://{{services.api.domain}}"
CONSOLE_WEB_URL = "https://{{services.web.domain}}"
SERVICE_API_URL = "https://{{services.api.domain}}"
APP_WEB_URL = "https://{{services.web.domain}}"
APP_API_URL = "https://{{services.api.domain}}"

# Web Configuration
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production" 