[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "pnpm start"
healthCheckPath = "/"
healthCheckTimeout = 300

[env]
NODE_ENV = "production"
EDITION = "SELF_HOSTED"
DEPLOY_ENV = "PRODUCTION"
NEXT_TELEMETRY_DISABLED = "1"
TZ = "UTC" 